server:
  port: 8090

spring:
  kafka:
    consumer:
      threads: 1
      bootstrap-servers: kafka:9092
      auto-offset-reset: earliest
      group-id: betvictor
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    mongodb:
      host: mongo-db

